# Generated by Django 2.2.1 on 2019-05-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCityTrafficDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cityCode', models.CharField(max_length=32)),
                ('bounds_lon', models.FloatField()),
                ('bounds_lat', models.FloatField()),
                ('yearPid', models.IntegerField()),
            ],
            options={
                'db_table': 'MainTrafficInfo',
            },
        ),
    ]
