# Generated by Django 2.2.1 on 2019-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScenceView', '0003_auto_20190512_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='temperature',
            field=models.CharField(max_length=16, verbose_name='气温'),
        ),
    ]
