# Generated by Django 2.2.1 on 2019-05-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScenceView', '0005_auto_20190515_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_data',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Traffic', to='ScenceView.JingQuDatabase', to_field='CityTableCode', verbose_name='景区pid'),
        ),
    ]
