# Generated by Django 2.2.1 on 2019-05-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScenceView', '0008_auto_20190522_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleflow',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='traffic_data',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='weather_data',
            name='pid',
        ),
        migrations.DeleteModel(
            name='JingQuDatabase',
        ),
        migrations.DeleteModel(
            name='PeopleFlow',
        ),
        migrations.DeleteModel(
            name='Traffic_Data',
        ),
        migrations.DeleteModel(
            name='Weather_Data',
        ),
    ]
