# Generated by Django 2.2.1 on 2019-05-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ScenceView', '0009_auto_20190530_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='JingQuDatabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, verbose_name='景区名字')),
                ('bounds_lon', models.FloatField(verbose_name='经纬度')),
                ('bounds_lat', models.FloatField(verbose_name='经纬度')),
                ('PeoplePid', models.IntegerField(verbose_name='景区ip')),
                ('CityCode', models.IntegerField(default=0, verbose_name='城市交通ip')),
                ('WeatherPid', models.CharField(max_length=32, verbose_name='天气情况ip')),
                ('PeopleTablePid', models.IntegerField(unique=True, verbose_name='景区表')),
                ('CityTableCode', models.IntegerField(unique=True, verbose_name='城市交通表')),
                ('WeatherTablePid', models.IntegerField(max_length=32, unique=True, verbose_name='天气情况表')),
            ],
            options={
                'db_table': 'ScenceInfoData',
            },
        ),
        migrations.CreateModel(
            name='Weather_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=32, verbose_name='日期')),
                ('detailTime', models.CharField(max_length=16, verbose_name='时间点')),
                ('state', models.CharField(max_length=32, verbose_name='天气状态')),
                ('temperature', models.CharField(max_length=16, verbose_name='气温')),
                ('wind', models.CharField(max_length=32, verbose_name='风力风向')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='ScenceView.JingQuDatabase', to_field='WeatherTablePid', verbose_name='景区pid')),
            ],
            options={
                'db_table': 'weather',
                'ordering': ['date', 'detailTime'],
            },
        ),
        migrations.CreateModel(
            name='Traffic_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=32, verbose_name='日期')),
                ('TrafficIndex', models.FloatField(verbose_name='交通拥堵指数')),
                ('detailTime', models.CharField(max_length=16, verbose_name='时间点')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Traffic', to='ScenceView.JingQuDatabase', to_field='CityTableCode', verbose_name='景区pid')),
            ],
            options={
                'db_table': 'traffic',
                'ordering': ['detailTime'],
            },
        ),
        migrations.CreateModel(
            name='PeopleFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('num', models.IntegerField(verbose_name='客流')),
                ('detailTime', models.CharField(max_length=16, verbose_name='时间点')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flow', to='ScenceView.JingQuDatabase', to_field='PeopleTablePid', verbose_name='景区pid')),
            ],
            options={
                'db_table': 'peopleFlow',
                'ordering': ['detailTime'],
            },
        ),
        migrations.AddIndex(
            model_name='weather_data',
            index=models.Index(fields=['pid'], name='景区pid'),
        ),
        migrations.AddIndex(
            model_name='weather_data',
            index=models.Index(fields=['date'], name='Day'),
        ),
        migrations.AddIndex(
            model_name='traffic_data',
            index=models.Index(fields=['pid'], name='景区pid'),
        ),
        migrations.AddIndex(
            model_name='traffic_data',
            index=models.Index(fields=['date'], name='Day'),
        ),
        migrations.AddIndex(
            model_name='peopleflow',
            index=models.Index(fields=['pid'], name='ScencePid'),
        ),
        migrations.AddIndex(
            model_name='peopleflow',
            index=models.Index(fields=['date'], name='Day'),
        ),
    ]
