# Generated by Django 2.2.1 on 2019-05-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScenceView', '0010_auto_20190530_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrastDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pid', models.IntegerField()),
                ('environment', models.IntegerField()),
                ('equipment', models.IntegerField()),
                ('peopleStream', models.IntegerField()),
                ('clean', models.IntegerField()),
                ('traffic', models.IntegerField()),
            ],
        ),
    ]
