# Generated by Django 2.2.1 on 2019-05-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScenceView', '0011_contrastdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContrastDetail',
        ),
    ]
