# Generated by Django 2.2.1 on 2019-06-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBrandRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌')),
                ('pid', models.IntegerField(unique=True, verbose_name='品牌id')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='MobileNetworkRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=32, verbose_name='网络占用率')),
                ('pid', models.IntegerField(verbose_name='id')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='MobileOperatorRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=32, verbose_name='运营商')),
                ('pid', models.IntegerField(verbose_name='id')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='MobileResolutionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=32, verbose_name='分辨率')),
                ('pid', models.IntegerField(verbose_name='id')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSystemRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=32, verbose_name=' 系统')),
                ('pid', models.IntegerField(verbose_name='id')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WetchatPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=32, verbose_name='公众号名字')),
                ('card', models.CharField(max_length=32, verbose_name='账号')),
                ('averageread', models.IntegerField(verbose_name='平均阅读量')),
                ('hightread', models.IntegerField(verbose_name='最高阅读量')),
                ('averagelike', models.IntegerField(verbose_name='平均点赞')),
                ('hightlike', models.IntegerField(verbose_name='最高点赞')),
            ],
        ),
        migrations.CreateModel(
            name='WetchatPublicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, verbose_name='关键词')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet.WetchatPublic', to_field='pid')),
            ],
        ),
        migrations.CreateModel(
            name='Wetchat_Ariticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='文章链接id号')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet.WetchatPublic', to_field='pid')),
            ],
        ),
        migrations.CreateModel(
            name='MobileTypeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_type', models.CharField(max_length=32, verbose_name=' 机型')),
                ('value', models.FloatField(verbose_name='占有率')),
                ('date', models.DateField(verbose_name='日期')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet.MobileBrandRate', to_field='pid', verbose_name='品牌标识')),
            ],
        ),
    ]
