# Generated by Django 2.2.1 on 2019-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='href',
            field=models.CharField(default='', max_length=32, verbose_name='省份入口'),
            preserve_default=False,
        ),
    ]
