# Generated by Django 2.2.1 on 2019-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_province_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='href',
            field=models.CharField(max_length=64, verbose_name='省份入口'),
        ),
    ]
