# Generated by Django 2.2.1 on 2019-06-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190617_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='href',
            field=models.CharField(default='', max_length=64, verbose_name='城市历史数据入口'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=64, verbose_name='城市历史数据链接')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City', to_field='citypid')),
            ],
        ),
    ]
