# Generated by Django 2.2.1 on 2019-06-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190617_0708'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historylist',
            table='historylist',
        ),
    ]
