# Generated by Django 2.2.1 on 2019-05-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebView', '0004_auto_20190512_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic_data',
            old_name='index',
            new_name='TrafficIndex',
        ),
    ]
