# Generated by Django 2.2.1 on 2019-05-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebView', '0006_auto_20190522_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather_data',
            options={'ordering': ['detailTime', 'date']},
        ),
    ]
