# Generated by Django 2.2.1 on 2019-05-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficView', '0002_auto_20190530_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearcitytraffic',
            options={'ordering': ['date']},
        ),
    ]
