# Generated by Django 2.2.1 on 2019-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficView', '0006_roadtraffic_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citytraffic',
            options={'ordering': ['detailTime']},
        ),
        migrations.RemoveField(
            model_name='citytraffic',
            name='data',
        ),
        migrations.RemoveField(
            model_name='citytraffic',
            name='time',
        ),
        migrations.AddField(
            model_name='citytraffic',
            name='TrafficIndex',
            field=models.FloatField(default=0, verbose_name='交通拥堵指数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citytraffic',
            name='detailTime',
            field=models.CharField(default=2019, max_length=16, verbose_name='时间点'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citytraffic',
            name='date',
            field=models.DateField(max_length=32, verbose_name='日期'),
        ),
    ]
