# Generated by Django 2.2.1 on 2019-06-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficView', '0009_auto_20190601_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadtraffic',
            old_name='DetailTime',
            new_name='detailtime',
        ),
    ]
